services:
  - type: web
    name: fukuyama-ai-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
