services:
  - type: web
    name: fukuyama-real-estate-api
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python -c "
      import os
      import sys
      sys.path.append('.')
      from api import app
      import uvicorn
      port = int(os.environ.get('PORT', 8000))
      uvicorn.run(app, host='0.0.0.0', port=port)
      "
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
